services:
  - type: web
    plan: free
    name: shubham
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m Adarsh
    repo: https://github.com/jhashubham242yt/WD_Filestreambot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FQDN
        sync: false
    autoDeploy: false
